/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wzx_ssdut_Hello */

#ifndef _Included_wzx_ssdut_Hello
#define _Included_wzx_ssdut_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wzx_ssdut_Hello
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wzx_ssdut_Hello_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
